import "@/app/globals.css";

import type { Metadata } from "next";
import { Sora } from "next/font/google";

import Footer from "./(components)/(footer)";
import Header from "./(components)/(header)";

const sora = Sora({
    subsets: ["latin"],
    weight: ["200", "400", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={sora.className}>
                <div id="body">
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
